In [1]:
#Slicing a list creates a copy of that list, slicing an array creates a view of that array (not a copy)
l= [323,42,3,24,-121,234,2] #--this is list
l

[323, 42, 3, 24, -121, 234, 2]

In [2]:
import numpy as np

In [5]:
a=np.array(l)
a

array([ 323,   42,    3,   24, -121,  234,    2])

In [7]:
#diff b/w list and array ...array can't have a different data types. only one type should be thier in array(any type)
l.pop() #pop is a function to bring out of list of last element(list(after. press tab to see more functions))

2

In [11]:
a.mean()

72.42857142857143

In [15]:
#MATRIX IS A two dimentional arrays. 
#slicing arrays
X=list(range(1,10))
print(X)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
Ary=np.array(X)
Ary

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# array has a peculiar behavior like if we need to assign a array using indexes like list we can do but we should be 
# in using special functions present in array
B=Ary[2:8] # we are just creating a seperate view like Ary array we are not assigning it to that python uses same space(bytes) 
            # to perform any operation
B


array([3, 4, 5, 6, 7, 8])

In [23]:
B[4]=9999

In [24]:
#now lets check the original array Ary
Ary
"""It will also gets changed"""

array([   1,    2,    3,    4,    5,    6, 9999,    8,    9])

In [25]:
B1=Ary.copy()

In [26]:
B1[2]=7777

In [27]:
B1

array([   1,    2, 7777,    4,    5,    6, 9999,    8,    9])

In [28]:
Ary

array([   1,    2,    3,    4,    5,    6, 9999,    8,    9])

In [ ]:
#now it wont change because of the copy function. 